openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
paths:
  /sessions:
    post:
      summary: Login with username and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: user123
                password: password123
      responses:
        '201':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  isAdmin:
                    type: boolean
                  sessionId:
                    type: integer
        '400':
          description: Invalid request or missing parameters
        '401':
          description: Invalid username or password

  /oAuth2Login:
    post:
      summary: Login with Google OAuth2
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: string
              example:
                credential: <Google OAuth2 Token>
      responses:
        '201':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  username:
                    type: string
                  isAdmin:
                    type: boolean
                  sessionId:
                    type: integer
        '400':
          description: Login unsuccessful or missing parameters

  /items:
    get:
      summary: Get a list of items
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Add a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created
        '400':
          description: Invalid input
  /items/{id}:
    get:
      summary: Get an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: Item ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
    put:
      summary: Update an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: Item ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Item updated
        '400':
          description: Invalid input
        '404':
          description: Item not found
    delete:
      summary: Delete an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: Item ID
      responses:
        '200':
          description: Item deleted
        '404':
          description: Item not found
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Tool
        price:
          type: string
          example: 6.99
        description:
          type: string
          example: Tammepuidust tool
